version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  mongo-data:
